-- Drop existing tables if they exist
DROP TABLE IF EXISTS TBL_MEDIA_METADATA;
DROP TABLE IF EXISTS TBL_TAGS_TO_MEDIA;
DROP TABLE IF EXISTS TBL_TAGS;
DROP TABLE IF EXISTS TBL_IDENTIFIED_FACES;
DROP TABLE IF EXISTS TBL_INVALID_FACES;
DROP TABLE IF EXISTS TBL_MEDIA_OBJECTS;
DROP TABLE IF EXISTS TBL_KNOWN_FACES;
DROP TABLE IF EXISTS TBL_image_tensors;
DROP TABLE IF EXISTS TBL_movie_hashes;


-- Create tbl_image_tensors table
CREATE TABLE public.tbl_image_tensors (
    id SERIAL PRIMARY KEY,
    filename TEXT,
    tensor_shape TEXT,
    tensor_pil BYTEA,
    hash_pil TEXT,
    tensor_cv2 BYTEA,
    hash_cv2 TEXT
);

-- Ensure sequence ownership
ALTER SEQUENCE public.tbl_image_tensors_id_seq OWNED BY public.tbl_image_tensors.id;

-- Create tbl_movie_hashes table
CREATE TABLE public.tbl_movie_hashes (
    id SERIAL PRIMARY KEY,
    filename TEXT NOT NULL,
    media_hash TEXT NOT NULL
);

-- Ensure sequence ownership
ALTER SEQUENCE public.tbl_movie_hashes_id_seq OWNED BY public.tbl_movie_hashes.id;

-- Create tbl_media_objects table
CREATE TABLE public.tbl_media_objects (
    media_object_id SERIAL PRIMARY KEY,
    orig_name VARCHAR(120) NOT NULL,
    new_name VARCHAR(30),
    orig_path VARCHAR(240) NOT NULL,
    new_path VARCHAR(120),
    media_type VARCHAR(20),
    media_create_date TIMESTAMP,
    location_class VARCHAR(60),
    location_type VARCHAR(60),
    location_name VARCHAR(200),
    location_display_name VARCHAR(200),
    location_city VARCHAR(60),
    location_province VARCHAR(60),
    location_country VARCHAR(60),
    tag_assigned INT DEFAULT 0,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(120),
    created_ip VARCHAR(20),
    is_active BOOLEAN DEFAULT TRUE,
    image_tensor_id INT,
    movie_hash_id INT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    FOREIGN KEY (image_tensor_id) REFERENCES public.tbl_image_tensors (id) ON DELETE SET NULL,
    FOREIGN KEY (movie_hash_id) REFERENCES public.tbl_movie_hashes (id) ON DELETE SET NULL
);

-- Ensure sequence ownership
ALTER SEQUENCE public.tbl_media_objects_media_object_id_seq OWNED BY public.tbl_media_objects.media_object_id;

-- Create tbl_media_metadata table
CREATE TABLE public.tbl_media_metadata (
    media_metadata_id SERIAL PRIMARY KEY,
    media_object_id INT NOT NULL,
    exif_tag VARCHAR(60),
    exif_data VARCHAR(255),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(30),
    created_ip VARCHAR(20),
    FOREIGN KEY (media_object_id) REFERENCES public.tbl_media_objects (media_object_id) ON DELETE CASCADE
);

-- Ensure sequence ownership
ALTER SEQUENCE public.tbl_media_metadata_media_metadata_id_seq OWNED BY public.tbl_media_metadata.media_metadata_id;

-- Create tbl_tags table
CREATE TABLE public.tbl_tags (
    tag_id SERIAL PRIMARY KEY,
    tag_name VARCHAR(60) NOT NULL UNIQUE,
    tag_desc VARCHAR(120),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(30),
    created_ip VARCHAR(20)
);

-- Ensure sequence ownership
ALTER SEQUENCE public.tbl_tags_tag_id_seq OWNED BY public.tbl_tags.tag_id;

-- Create tbl_tags_to_media table
CREATE TABLE public.tbl_tags_to_media (
    tags_to_media_id SERIAL PRIMARY KEY,
    media_object_id INT NOT NULL,
    tag_id INT NOT NULL,
    UNIQUE (media_object_id, tag_id),
    FOREIGN KEY (media_object_id) REFERENCES public.tbl_media_objects (media_object_id) ON DELETE CASCADE,
    FOREIGN KEY (tag_id) REFERENCES public.tbl_tags (tag_id) ON DELETE CASCADE
);

-- Ensure sequence ownership
ALTER SEQUENCE public.tbl_tags_to_media_tags_to_media_id_seq OWNED BY public.tbl_tags_to_media.tags_to_media_id;

-- Create tbl_known_faces table
CREATE TABLE public.tbl_known_faces (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    encoding BYTEA NOT NULL
);

-- Ensure sequence ownership
ALTER SEQUENCE public.tbl_known_faces_id_seq OWNED BY public.tbl_known_faces.id;

-- Create tbl_identified_faces table
CREATE TABLE public.tbl_identified_faces (
    id SERIAL PRIMARY KEY,
    media_object_id INT,
    face_name VARCHAR(255),
    FOREIGN KEY (media_object_id) REFERENCES public.tbl_media_objects (media_object_id) ON DELETE CASCADE
);

-- Ensure sequence ownership
ALTER SEQUENCE public.tbl_identified_faces_id_seq OWNED BY public.tbl_identified_faces.id;

-- Create tbl_invalid_faces table
CREATE TABLE public.tbl_invalid_faces (
    media_object_id INT,
    "top" INT,
    "right" INT,
    "bottom" INT,
    "left" INT,
    PRIMARY KEY (media_object_id, "top", "right", "bottom", "left"),
    FOREIGN KEY (media_object_id) REFERENCES public.tbl_media_objects (media_object_id) ON DELETE CASCADE
);

-- Preload tags into tbl_tags
INSERT INTO public.tbl_tags (tag_name, tag_desc, created_by, created_ip) VALUES
    ('Chris Orr', 'Chris Orr', 'system', '127.0.0.1'),
    ('Tressa List', 'Tressa List', 'system', '127.0.0.1'),
    ('Natasha Orr', 'Natasha Orr', 'system', '127.0.0.1'),
    ('Hunter Orr', 'Hunter Orr', 'system', '127.0.0.1'),
    ('JD Cameron', 'JD Cameron', 'system', '127.0.0.1'),
    ('Curt Sanders', 'Curt Sanders', 'system', '127.0.0.1'),
    ('Tammy Sanders', 'Tammy Sanders', 'system', '127.0.0.1'),
    ('Bev List', 'Bev List', 'system', '127.0.0.1'),
    ('Gerard List', 'Gerard List', 'system', '127.0.0.1'),
    ('Patrick Giroux', 'Patrick Giroux', 'system', '127.0.0.1'),
    ('Holly Giroux', 'Holly Giroux', 'system', '127.0.0.1'),
    ('David Webster', 'David Webster', 'system', '127.0.0.1'),
    ('The Lake', 'Our current boat', 'system', '127.0.0.1'),
    ('Engines', 'Photos related to the engines', 'system', '127.0.0.1'),
    ('Miraloma', 'Photos related to Miraloma on the Cove', 'system', '127.0.0.1');

-- Insert face encodings into tbl_known_faces
INSERT INTO public.tbl_known_faces (id, name, encoding) VALUES (1, 'Natasha Orr', DECODE('AAAAwPMmwb8AAADAwoisPwAAAGD6U6U/AAAAIHxItb8AAAAAY/nGvwAAAKAPN7C/AAAAgHkOqT8AAACgZIWrvwAAAKCAlsY/AAAAwOZgu78AAADgMqi9PwAAAAAhu4i/AAAAABEt078AAAAgeSu0PwAAAEAXlp+/AAAAIAluxz8AAAAAYOW7vwAAACDMsMi/AAAAAA1av78AAADA5c+2vwAAACBJCLI/AAAAwLhQsD8AAAAAvKSmPwAAACA5Hrc/AAAAADUexr8AAADgm7DTvwAAACC/vq6/AAAAQBRQr78AAACA1TuWvwAAACBRh6G/AAAAgMf9cz8AAAAgy57BPwAAAKD9qsC/AAAAgDQNpj8AAADgtjejPwAAAOBP5bc/AAAA4GzevL8AAABAt7zCvwAAAGBvmdI/AAAAgGq4nz8AAADgH+zRvwAAAODJ3qO/AAAAwEy0mj8AAABgDmnNPwAAAACNiss/AAAAIMETUT8AAAAA40m2PwAAAEARorO/AAAAALF7pD8AAABg4SbXvwAAAOBvm7E/AAAAAOM3zD8AAABgAe6ovwAAACCrras/AAAAoJHsqz8AAABAi+DFvwAAAAANE3k/AAAAAHONxT8AAABADcfKvwAAAKCA+6C/AAAAIMbKsj8AAAAAhxG9vwAAAECD7am/AAAAoMiWwb8AAACAXxHLPwAAACD2sMM/AAAAgFVHwb8AAAAAJfG7vwAAAOADqsw/AAAAoDduz78AAAAghH67vwAAAIDjQbI/AAAAwLPFw78AAACABz7MvwAAAECku86/AAAAQFqdmD8AAADAwMfYPwAAAMBHVM4/AAAAgNzRqb8AAACAIaewPwAAAGBkDKm/AAAAwPjXjj8AAAAAeEOxPwAAAMB9yLo/AAAAoDznqr8AAADALK6wvwAAAMDlOrK/AAAA4HVHrj8AAAAASKLMPwAAAGAy9py/AAAAYLwIrb8AAADgDHXOPwAAAMD0BbQ/AAAAYHuTgr8AAACAwb+DvwAAAKCx76A/AAAAwM2Dpb8AAADgaT2XvwAAAIBPwr2/AAAAYBH5pT8AAAAA48JsvwAAAIApvIS/AAAAwA72hL8AAABgN3fCPwAAAEBM7sK/AAAAoMUowT8AAABgdlO0vwAAAGBGAKy/AAAAQIyEtb8AAADAj/atvwAAAADgvbm/AAAAgEDNk78AAACgVNu8PwAAACCL8Mu/AAAAYAOtwj8AAADAOmTKPwAAAMAUz1U/AAAAwDvqwj8AAAAAK0i0PwAAAABsjaY/AAAAYJI4pz8AAADAw4OyvwAAACCiKNG/AAAAgGGvp78AAAAgDlnDPwAAAECgTHy/AAAAgGRhqj8AAADA9aWxPw==', 'base64')) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, encoding=EXCLUDED.encoding;
INSERT INTO public.tbl_known_faces (id, name, encoding) VALUES (2, 'JD Cameron', DECODE('AAAA4DU9vL8AAABAw/2mPwAAAIBs/pC/AAAAwNKQsL8AAADApUvGvwAAAMA3vb6/AAAAwOeTpj8AAACA50qgvwAAAABWjL4/AAAAAFmuq78AAACAHQ3JPwAAAGCNwbW/AAAAwP5ozb8AAABg16GovwAAAABA7aS/AAAAwChjtj8AAABgOPi+vwAAAEDb3L+/AAAAQDztvL8AAACgf8y1vwAAAGAaWLY/AAAAgD3ZOr8AAABgyDugvwAAAIAFyb8/AAAAQBrptr8AAADgZNDSvwAAAKBtd6S/AAAAAO2ts78AAACAlTeyPwAAAKBXLrm/AAAAwPSdsD8AAADAQUPHPwAAAODkKru/AAAAoE1Lsb8AAABgs2ucPwAAAGDFX8E/AAAAAEjdsr8AAADAOfG8vwAAAABupM8/AAAAAM6Cgb8AAAAgNsvBvwAAAODpcau/AAAA4D7ppD8AAABgraXVPwAAACAvacA/AAAAoCVXlL8AAABA2oi5PwAAAIDO+bO/AAAAICAayT8AAAAAJ4HOvwAAAABI9Kc/AAAAADlzxz8AAABgK0y+PwAAAMCiMrk/AAAAwP54uT8AAACA/YO9vwAAAKC0Zbk/AAAAgHi0yj8AAADAH43HvwAAAKC8ALg/AAAAID/KsD8AAACg+9y7vwAAAABv8bO/AAAAIDHLxb8AAABAjl7LPwAAAOABTbM/AAAAIG9ftb8AAACgU0XAvwAAAIA4DMA/AAAAoEaoxL8AAAAAuy7HvwAAAECAErs/AAAAoFsPwr8AAAAgqjvAvwAAAGDoDtC/AAAAwN7CnT8AAACgAFTXPwAAAIDuT8g/AAAAIPsIwr8AAACgIJqsPwAAAAC99Zu/AAAAIOohkr8AAAAAqo+6PwAAAGBQOLI/AAAAIK1QwL8AAADAPTuSvwAAACC+SsC/AAAAAMI+pj8AAADA8mnKPwAAAID3N3e/AAAAwBErsb8AAABgix/FPwAAAMB4uq0/AAAAgIGakT8AAAAgl3OePwAAAMDiZ6+/AAAAwBl2tL8AAADACkmPPwAAAKAgFrS/AAAAIGrnob8AAAAgaIHEPwAAAIDwLMK/AAAAALZsgr8AAABgIN+TPwAAAEArXce/AAAAIF4Wwz8AAADA38OfvwAAAOB+QLM/AAAAgAAafz8AAAAAXNyxvwAAAICKosG/AAAA4E7VsT8AAACgMELGPwAAAIA4Uc2/AAAAoPLsyz8AAAAAFA7APwAAAMCAVrU/AAAAQA1+vz8AAACgK9u7PwAAAEDH7aI/AAAAIHRajb8AAAAg/iy0vwAAAICRa8G/AAAAQOH7qr8AAADA1OnBPwAAAEB3T5o/AAAAwFpRsz8AAAAARU5Nvw==', 'base64')) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, encoding=EXCLUDED.encoding;
INSERT INTO public.tbl_known_faces (id, name, encoding) VALUES (3, 'Chris Orr', DECODE('AAAAAPhtwL8AAAAgs4STvwAAAIC+9po/AAAA4Lphp78AAADgyKq5vwAAAABVI8O/AAAAQOv0uD8AAABA4oGRvwAAAOA6ubY/AAAAICr1tD8AAADAz7nKPwAAAKAMXqu/AAAAwEgKyr8AAAAgYYe1vwAAAMBxULA/AAAAIAjClT8AAACAQnHBvwAAAMBW+I+/AAAA4PlCu78AAABglEesvwAAAOBxq7A/AAAAABHheL8AAADgZIm0PwAAAOARhao/AAAAYGCDub8AAABAYl7TvwAAAMDTSbS/AAAAQLBUw78AAAAAc8u9PwAAAGDFdsC/AAAAQIPCoD8AAAAAUk+/PwAAAIDU/sa/AAAAgKf1wb8AAADAuICMPwAAAICrEbE/AAAAYNfxtL8AAABgWfm1vwAAAIBiz80/AAAAwD0Dpr8AAAAAAFPFvwAAAEAlxZi/AAAA4EKJuT8AAACAJrfLPwAAAGC1g8o/AAAAIHATiD8AAABgz4mdvwAAAIBu7oY/AAAAYBp6vj8AAACgffvQvwAAAKC3F7A/AAAAwNk1wT8AAABAj3azPwAAAAAVILM/AAAAALZSwj8AAAAA5gzCvwAAAIBM+rU/AAAAgNHWtj8AAAAgbyjOvwAAACCOTq8/AAAAgLurqT8AAACAKT2wvwAAAMCo46O/AAAA4NUGv78AAABABkS9PwAAAMDLQbE/AAAAoO3wsr8AAADg4XCjvwAAAMCss5E/AAAAoKkTxb8AAADgzQdwPwAAAAC9eMI/AAAAgKOtwL8AAAAgY/jGvwAAAKDbncq/AAAA4LJCrj8AAABAk3TXPwAAAGACksQ/AAAAAH4dwL8AAACAFc6lPwAAAIBUX6i/AAAAQLRas78AAADA2+O1PwAAAGCO636/AAAAwHmDt78AAAAA5h6SPwAAAGC/2LW/AAAAAJI2pD8AAADgvQO0PwAAAAARQnM/AAAAgPsjeL8AAACAauPHPwAAAMCvx6K/AAAAwJtgrj8AAABAlP+wPwAAAMA7wZe/AAAAYC8stL8AAACge7SZvwAAAAAXjrW/AAAAgIEZZT8AAACAjZ25PwAAAMBvRM6/AAAAoOwBgD8AAABATIN3PwAAAGDnEsa/AAAAwBwpuj8AAACA4zCYPwAAAADKjpQ/AAAAQK7ucb8AAACAa0ivvwAAAICBobO/AAAAYBXQrz8AAADgww3BPwAAAGDgXtC/AAAAgLqL0T8AAAAA6snCPwAAAEClgrG/AAAAIGBsvz8AAADAKMKYPwAAAOBf9as/AAAAYJXEtb8AAABAvuiIPwAAAACGgLS/AAAAgO5Zj78AAABAXcyzPwAAAKBmkIC/AAAAwLUCtj8AAADAwOWavw==', 'base64')) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, encoding=EXCLUDED.encoding;
INSERT INTO public.tbl_known_faces (id, name, encoding) VALUES (4, 'David Webster', DECODE('AAAAAFrnor8AAABgbJDBPwAAAKCsBKA/AAAAYLXjqL8AAADg7Mi7vwAAAMAArY6/AAAAwCGliL8AAADA1MGmvwAAACB5oL8/AAAAABzOtb8AAABgyku3PwAAAAC6Pru/AAAAQPOw0r8AAABgCMutPwAAAODUP7a/AAAAIDYvwj8AAACAz4bDvwAAAODjYq6/AAAAYP1IwL8AAACA3/KyvwAAAIAX4mM/AAAAYPxJuz8AAADgAzOqvwAAAMCdb5w/AAAAAKXZpb8AAABA5D/TvwAAAMBDbrG/AAAAAAPsmr8AAAAghWKZPwAAAAAKQbq/AAAAgB8aYT8AAAAgUh23PwAAACCG/cK/AAAAwKdYlb8AAAAgR7mpPwAAAEBE3Kk/AAAAQAgJvr8AAACA9e+lvwAAAGBHn8Q/AAAAgI8ewT8AAADg3iC/vwAAAEC5KJq/AAAAQFKTkT8AAACAiCfUPwAAAMCqXcs/AAAAgHZsqz8AAAAgOfmSvwAAAKBHuba/AAAAACeNkj8AAAAg1mbRvwAAAADoa5U/AAAA4G2syD8AAAAA02apPwAAAMAxrrk/AAAAIOKStj8AAAAALLa9vwAAAKCQG5k/AAAAgKYksz8AAACg1BnBvwAAAGCnE4M/AAAAgJCnvD8AAADAXS+7vwAAAGDa67O/AAAAIA0UiL8AAADgCpDHPwAAAIDTVrA/AAAAAIHOub8AAACAByy1vwAAAKD2C8M/AAAA4Htwyr8AAABg0e+3vwAAAEBbXKK/AAAAwB//kr8AAABg9Vy7vwAAAOC8gNC/AAAAgMoSoz8AAABgWPrXPwAAAKDXqcY/AAAAIDcYxL8AAAAgOlGdPwAAAMApQ6W/AAAAgGZIiL8AAAAgqzbEPwAAAOC1vrA/AAAAwKqWw78AAACADtGqvwAAAOB/fJa/AAAAgOKGqj8AAACACq/APwAAAGCMGqK/AAAAgPjyor8AAABAMc3DPwAAAACQlTy/AAAAADAoob8AAAAAC6mvPwAAAMBDIqa/AAAAwHHNsL8AAACAIlSnvwAAAKC5D7+/AAAA4Fp3p78AAABgIM65PwAAAGC6eMG/AAAAAK8vjL8AAABgWBfBPwAAAAA/eMi/AAAAADhcwj8AAACAWE+XPwAAAKAH1Le/AAAAYAippj8AAAAgWWiAvwAAAEApdsW/AAAAgHXCQj8AAAAAOvrIPwAAAKB4t82/AAAAYCdWxz8AAADA47XFPwAAACDDRq2/AAAAoMTAuT8AAADgvbi+PwAAAIBm4LY/AAAAALCBdz8AAABAAUOgvwAAAAAarrm/AAAAwJ9/wb8AAACAsP+xPwAAAAAaTq8/AAAA4OpUmj8AAACgn5Skvw==', 'base64')) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, encoding=EXCLUDED.encoding;
INSERT INTO public.tbl_known_faces (id, name, encoding) VALUES (5, 'Hunter Orr', DECODE('AAAA4AOHx78AAABgUh2dvwAAAED4toE/AAAA4LeJpb8AAABAqBLGvwAAAMBM+Ze/AAAAQIZIkD8AAAAAYKonPwAAACDQfME/AAAAYD/8s78AAACgCcTHPwAAAECp05W/AAAA4L/+0b8AAABAcfOqvwAAAIBMIKW/AAAAQEVeuT8AAACAfsa6vwAAAACBFcG/AAAAgKGItb8AAACAOQm+vwAAAOCGS6s/AAAAAB0Wqb8AAADgsq2gvwAAAEC/PbQ/AAAAYMXFxL8AAACgB1rTvwAAAKDqI7a/AAAAIF/HvL8AAADA1rOoPwAAAICu9cC/AAAAQAFJjb8AAACAY06nPwAAAEDowre/AAAAAPXYtr8AAACATH2xPwAAAIC7BL0/AAAAgLSusL8AAAAg5923vwAAAMCaGs0/AAAAgPqbsr8AAAAgu0LEvwAAAABjS5C/AAAAgDclsz8AAACgblDPPwAAACBThsI/AAAAgMzqtj8AAAAAg12RPwAAAACQ/rS/AAAAwPnZwT8AAADAKF/UvwAAAIAmKbs/AAAAgA9ExD8AAACgVICyPwAAACBA5qI/AAAAADOPxD8AAACgPwfCvwAAAIC+jak/AAAAwCmTyj8AAADgkHXMvwAAAGDIXLU/AAAAQJxrer8AAACAkVG3vwAAAMCWhae/AAAAAN/ysb8AAACg6gjJPwAAAEBk2rw/AAAAIFTgwL8AAADg77G5vwAAAIB+/8c/AAAAQMgHyL8AAAAAQQqbvwAAAMBAOr0/AAAA4HJxsr8AAADg/PLMvwAAAMBcgs6/AAAAgCdVwD8AAACArujdPwAAAEB2os4/AAAA4MPCuL8AAAAgcZyuPwAAAIAoan+/AAAAQHsbqb8AAADgRKK2PwAAAODfA7A/AAAAYMksxL8AAACAZHqzvwAAAEBmVrS/AAAAQNomrD8AAACgySbBPwAAAEDwnac/AAAAAKlngL8AAAAAezPJPwAAACCp56U/AAAAwI76oD8AAACANL6xPwAAAGCxE68/AAAAIHNGv78AAACA8VWevwAAAKCljLC/AAAAQLoAmr8AAACAsfbIPwAAAKBlvbu/AAAAYPfdtD8AAABARQS3PwAAAMBVxMG/AAAAQOkUpj8AAABgV0m7vwAAAEBthqO/AAAAAFTJXL8AAADABC+jvwAAAICe/rm/AAAAAP43hz8AAACgPx/APwAAAAASmtS/AAAAYEfIxD8AAAAAFzvFPwAAAAD2iI0/AAAA4NLgwT8AAADAxoG8PwAAAIBEEnK/AAAAwE0usT8AAABA8HC0vwAAAOCXrMK/AAAAwH/Epr8AAAAAhoi4PwAAACDPb6i/AAAAIEyctD8AAAAAt2Rmvw==', 'base64')) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, encoding=EXCLUDED.encoding;
INSERT INTO public.tbl_known_faces (id, name, encoding) VALUES (6, 'Tressa List', DECODE('AAAA4MNxwb8AAADAioShPwAAAOC4h6c/AAAAYN3or78AAADAtZfMvwAAACCOorS/AAAAALeAdr8AAAAAC2SxvwAAAGBWCLM/AAAAoJJUub8AAADAgl2/PwAAAKCN/cC/AAAAwC5yw78AAACAjvS4PwAAAECroLe/AAAAoAe9xT8AAACA2P/DvwAAAECkR8m/AAAAgCARy78AAACAGFrFvwAAAMBu3Km/AAAAgMKfq78AAAAAi559vwAAAKDnEMI/AAAAoJbdwb8AAABgPYfMvwAAAKDOe6W/AAAAQIaXsb8AAADA6nW8PwAAAMD7gr2/AAAAYDZqk78AAAAALfK6PwAAAMCqnMW/AAAAgHB6ib8AAADAB3qzPwAAACCbQa0/AAAAYPafs78AAACgzJi7vwAAAMCECNA/AAAAoMu9q78AAACgr43KvwAAAGCzdaK/AAAAYH9Ouz8AAABA52bSPwAAAOCj080/AAAAgPbwkb8AAABA+vijPwAAACA3fZ2/AAAAoKqXwz8AAACgpSnUvwAAAAAd8rI/AAAAoDMLyD8AAADgpK+NPwAAACDIO8E/AAAAgHA7sj8AAAAgtVLEvwAAAIDblJU/AAAAoHPOzT8AAAAA9EXBvwAAAOD257U/AAAAIGpPrz8AAADgqObBvwAAAMDK5rC/AAAAwKcIxL8AAACAogLMPwAAAEDa68M/AAAAoAv/wr8AAACARprJvwAAAMB22cc/AAAAoDfix78AAACAW9SGvwAAAMBJMrs/AAAAYKH5tL8AAADAvXa8vwAAAOAJF9C/AAAAALoBdD8AAABg5+XZPwAAAIBgXsQ/AAAAIMZ7wL8AAAAA4JYOPwAAAAAEZK+/AAAAgG2Opr8AAAAAVZGIvwAAAKD19Ls/AAAAoGr/t78AAADAAoWkvwAAAOBBLLK/AAAAgJIEoT8AAACAbXrGPwAAAEC93ZK/AAAAoGKbir8AAADAUzjCPwAAAEDATJ0/AAAAIPzrwL8AAACAvW2LPwAAAODqGMA/AAAAQPiAy78AAADAgyKzvwAAAKDLYbi/AAAAIEtyhL8AAAAAJGyWvwAAAGA33q6/AAAAAOK1qL8AAABgA9yyPwAAAEACS76/AAAAwFWdyj8AAABA9bW5vwAAAABaX4K/AAAAIHr0xL8AAAAgx7uvvwAAAIB5I5G/AAAAgAFrgz8AAABgkArAPwAAAODwKtC/AAAAAPqJwD8AAADA5ofFPwAAAADv56I/AAAAIFyzwj8AAABAptSaPwAAAMDmC6Q/AAAAAIKslj8AAADAR8aHPwAAAKDmhbW/AAAAQLxyuL8AAAAgIcGgPwAAAIDAs6m/AAAAwN9bfb8AAABgPCSpPw==', 'base64')) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, encoding=EXCLUDED.encoding;
-- Add more insert statements as needed

-- Grant permissions to the specified user
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.tbl_media_objects TO mediauser;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.tbl_media_metadata TO mediauser;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.tbl_tags TO mediauser;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.tbl_tags_to_media TO mediauser;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.tbl_known_faces TO mediauser;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.tbl_identified_faces TO mediauser;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.tbl_invalid_faces TO mediauser;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.tbl_image_tensors TO mediauser;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.tbl_movie_hashes TO mediauser;

-- Grant permissions on all sequences in the public schema
DO $$
DECLARE
    seq RECORD;
BEGIN
    FOR seq IN
        SELECT schemaname, sequencename
        FROM pg_sequences
        WHERE schemaname = 'public'
    LOOP
        EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %I.%I TO mediauser', seq.schemaname, seq.sequencename);
    END LOOP;
END
$$;